name: Sync API to Supabase
on:
  schedule:
    - cron: '0 8 * * *'  # Executa diariamente às 8h UTC (5h Brasília)
  workflow_dispatch:       # Permite execução manual

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install \
            pandas \
            requests \
            supabase \
            urllib3 \
            python-dotenv

      - name: Executar script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          python sync_api.py
